language: node_js
node_js:
  - "11"
script:
  - npm run doc
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  local_dir: docs
  github_token: $GITHUB_TOKEN
  on:
    branch: master